version: '3'

services:

  vueapp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:5173"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development

  vueapp-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
  
  nginx-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "80:80"
